homepage/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, register_converter
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('', indexMain, name='indexMain'),
    path('transaction/', indexTransaction, name='indexTransaction'),
    path('kritik/', kritik, name="kritik"),
    path('getKritik/', getKritik, name="getKritik"),
    path('signup/', signUp, name="signup"),
    path('login/', loginUser, name="loginUser"),
    path('logout/', logoutUser, name="logoutUser"),
    path('apd/', apd, name="apd"),
    path('handsanitizer/', handsanitizer, name="handsanitizer"),
    path('masker/', masker, name="masker"),
    path('product/<str:pk>', indexProduct, name='indexProduct'),
    path('review/<str:pk>', indexReview, name='indexReview'),
    path('postReview/<str:pk>', postReview, name='postReview'),
    path('cariusername/', cariNamaAkun, name="cariNamaAkun"),
    path('searchusername/', searchUsername),
    # path('category/', category, name="category"),
   
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
from django.core.validators import *
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.contrib.auth.models import User

class Jenis(models.Model):
    pilihanJenis = (
        ('APD', 'APD'),
        ('Masker', 'Masker'),
        ('Hand Sanitizer', 'Hand Sanitizer')
    )
    nama = models.CharField(max_length=120, choices=pilihanJenis)

    def __str__(self):
        return self.nama

class Product(models.Model):

    nama = models.CharField(max_length=120)
    harga = models.IntegerField()
    deskripsi = models.TextField()
    jenis = models.ForeignKey(Jenis, null=True, on_delete=models.SET_NULL)
    stok = models.IntegerField()
    gambar = models.TextField()

    def __str__(self):
        return self.nama

class Transaction(models.Model):

    orderId = models.CharField(max_length=120)
    customer = models.CharField(max_length=120)
    transDate = models.DateTimeField(auto_now=True)
    produk = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    noHP = models.CharField(max_length=12)
    alamat = models.TextField()

    def __str__(self):
        return self.customer

class Review(models.Model):

    pilihanRate = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    produk = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    pengulas = models.ForeignKey(User, on_delete=models.CASCADE)
    headline = models.CharField(max_length=150)
    ulasan = models.TextField()
    bintang = models.IntegerField(choices=pilihanRate, default=5)
    tanggal = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.headline + " "+ self.produk.nama

class Kritik(models.Model):
    name = models.CharField(max_length=50, blank=True)
    message = models.CharField(max_length=300)

    def get_dict(self):
        return {
            'name':self.name,
            'message':self.message
        }
    
    def __str__(self):
        return self.name

        return self.headline + " "+ self.produk.name

homepage/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms import fields
class TransactionCreateForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = '__all__'
        widgets = {
            'orderId': forms.HiddenInput(attrs={
                'class': 'form-control'
            }),
            'customer': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'produk': forms.HiddenInput(attrs={
                'class': 'form-control'
            }),
            'transDate': forms.HiddenInput(attrs={
                'class': 'form-control'
            }),
            'noHP': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'alamat': forms.Textarea(attrs={
                'class': 'form-control'
            }),
        }

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=30, required=False, help_text='Optional.')
    full_name = forms.CharField(max_length=30, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ('username', 'full_name','email', 'password1', 'password2')

class KritikForm(ModelForm):
    isi = forms.CharField(widget=forms.Textarea({'class' : 'form-control','maxlength':'100', 'placeholder':'Bye-Covid menurut saya...'}), label='')
    class Meta:
        model = Kritik
        fields = ['isi']

class Kritik2Form(forms.Form):

    message = forms.CharField(label="kritik & saran", widget=forms.Textarea(attrs={
        'rows': 6,
        'style': 'resize:none;',
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'bagus...',
        'required': True,
        'id':'message_input'
    }))


class ReviewPageCreateForm(forms.Form):
    pilihanRate = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    headline = forms.CharField(required = False ,widget= forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Plese enter your headline',
    }))
    ulasan = forms.CharField(required = False, widget= forms.Textarea(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Please enter your review',
    }))
    bintang = forms.IntegerField(required=False,widget= forms.Select(choices = pilihanRate,attrs={
        'class': 'form-control',
        'placeholder' : 'Please enter the star',
    }))

homepage/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from datetime import datetime, date
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core import serializers
from django.http.response import HttpResponseRedirect
import json
from django.contrib.auth.decorators import login_required


from django.shortcuts import get_object_or_404

# Create your views here.
def indexMain(request):
    return render(request, 'landingPage.html')


def indexTransaction(request):
    transactions = Transaction.objects.all()

    context = {
        'transactions': transactions,
    }
    return render(request, 'transactionPage.html', context)

# def indexTransaction(request):
#     form = TransactionCreateForm(request.POST)

#     data = {}
    
#     if request.is_ajax():
#         if form.is_valid():
#             form.save()
#             # data['orderId'] = form.cleaned_data.get('orderId')
#             data['customer'] = form.cleaned_data.get('customer')
#             # data['transDate'] = form.cleaned_data.get('transDate')
#             # data['produk'] = form.cleaned_data.get('produk')  
#             data['noHP'] = form.cleaned_data.get('noHP')
#             data['alamat'] = form.cleaned_data.get('alamat')
#             return JsonResponse(data)

#     context = {
#         'form': form,
#     }

#     return render(request, 'transactionPage.html', context)

def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, "Successfully created a user with username {}".format(username))
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form' : form})

def loginUser(request): 
    if request.method == 'POST': 
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Logged in as {}'.format(username))
            return redirect('/')
        else:
            messages.error(request, 'Username or password is incorrect')
    return render(request, 'login.html')

def logoutUser(request):
    logout(request)
    messages.success(request, 'Successfully logged out!')
    return redirect('/')


def apd(request):
    return render(request, 'apd.html', {'apd_list': Product.objects.filter(jenis__nama__contains='APD')})

def masker(request):
    return render(request, 'masker.html', {'masker_list': Product.objects.filter(jenis__nama__contains='Masker')})

def handsanitizer(request):
    return render(request, 'handsanitizer.html', {'handsanitizer_list': Product.objects.filter(jenis__nama__contains='Hand Sanitizer')})

def indexProduct(request, pk):
    selectedProduct = Product.objects.get(id=pk)
    orderIdTmp = selectedProduct.nama
    print(orderIdTmp)
    initial_data = {
        'orderId': orderIdTmp,
        'transDate': datetime.now(),
        'produk': selectedProduct,
    }
    form = TransactionCreateForm(request.POST or None, initial=initial_data)
    print(initial_data)
    # reviews = Review.objects.filter(produk=selectedProduct)
    if form.is_valid():
        print('save berhasil')
        form.save()
        selectedProduct.stok -= 1
        selectedProduct.save()
        messages.success(request, 'Produk berhasil dipesan')
    else:
        print(form.errors)
        print("gagal")

    context = {
        'selectedProduct': selectedProduct,
        'form': form,
        # 'reviews': reviews,
    }
    return render(request, 'productPage.html', context)

# def category(request):
#     return render(request,'category.html')

# def cari(request):
#     q = request.GET['q']
#     hasil = []
#     products = Product.objects.all()
#     for i in products:
#         try:
#             price = int(q)
#             if(price>=int(i.harga)):
#                 hasil.append({
#                     'nama':i.nama,
#                     'harga':i.harga,
#                     'jenis':i.jenis,
#                     'stok':i.stok,
#                     'gambar':i.gambar
#                 })
#         except:
#             if(q.lower()==i.nama.lower()):
#                 hasil.append({
#                     'nama':i.nama,
#                     'harga':i.harga,
#                     'jenis':i.jenis,
#                     'stok':i.stok,
#                     'gambar':i.gambar
#                 })
#     data={
#         'hasil':hasil
#     }
#     return JsonResponse(data, safe=False)

# def kritik(request):
#     username = 'anon'
#     if request.user.is_authenticated:
#         username = request.user
#         # print(username)

#     if request.POST:
#         nama = username
#         isi = request.POST.get('isi')
#         Kritik.objects.create(nama=nama, isi=isi)
#         return HttpResponseRedirect('/category/')
#     else:
#         form = KritikForm()
#         kritiks = Kritik.objects.all()

#         for kritik in kritiks:
#             print(kritik)
        
#         context = {
#             'kritiks':kritiks,
#             'form':form
#         }
#         return render(request, 'category.html', context)

# def kritikajax(request):
#     argument = request.GET['q']
#     # argument = request.POST.get('q', none)
#     username = request.user
#     Kritik.objects.create(nama=username, isi=argument)
#     datastr = serializers.serialize("json", Kritik.objects.all())
#     data = json.loads(datastr)

#     return JsonResponse(data, safe=False)

@login_required(login_url="/login")
def kritik(request):
    response = {}
    if request.method == 'POST':
        if request.is_ajax():
            kritik_form = Kritik2Form(request.POST)
            if kritik_form.is_valid():
                kritik = Kritik()
                kritik.name = request.user.username
                kritik.message = kritik_form.cleaned_data['message']
                kritik.save()
                return JsonResponse({'success':True})
        return JsonResponse({'success':False})
    else:
        form = Kritik2Form()
        response = {'form':form}
        response['data'] = Kritik.objects.all()
        return render(request, 'kritik.html',response)


def getKritik(request):
    userReq = Kritik.objects.all().values()
    lst = list(userReq)
    #print(lst)
    return JsonResponse(lst, safe=False)


def indexReview(request, pk):
    user = request.user
    form = ReviewPageCreateForm()
    selectedProduct = get_object_or_404(Product,id=pk)
    data = {
        'produk': selectedProduct
    }
    review = Review.objects.filter(produk=selectedProduct)
    total = 0
    jumlah_bintang_1 = 0
    jumlah_bintang_2 = 0
    jumlah_bintang_3 = 0
    jumlah_bintang_4 = 0
    jumlah_bintang_5 = 0
    for rev in review:
        total += rev.bintang
        if rev.bintang == 1:
            jumlah_bintang_1 += 1
        elif rev.bintang == 2:
            jumlah_bintang_2 += 1
        elif rev.bintang == 3:
            jumlah_bintang_3 += 1
        elif rev.bintang == 4:
            jumlah_bintang_4 += 1
        elif rev.bintang == 5:
            jumlah_bintang_5 += 1
    try:
        avg = total / len(review)
        avg = round(avg, 2)
    except ZeroDivisionError:
        avg = 0
    avg = round(avg, 2)
    context = {
        'selectedProduct': selectedProduct,
        'review': review,
        'average': avg,
        'form' : form,
        'postPK' : pk,
        'user' : user,
        'bintang1': jumlah_bintang_1,
        'bintang2': jumlah_bintang_2,
        'bintang3': jumlah_bintang_3,
        'bintang4': jumlah_bintang_4,
        'bintang5': jumlah_bintang_5

    }
    return render(request, 'reviewPage.html', context)


def postReview(request, pk) :
    selectedProduct = Product.objects.get(id=pk)
    data ={
        'produk' : selectedProduct
    }
    response_data = {}
    if request.method == "POST":
        print(request.POST)
        headline = request.POST.get('headline')
        ulasan = request.POST.get('ulasan')
        bintang = request.POST.get('bintang')

        response_data['headline'] = headline
        response_data['ulasan'] = ulasan
        response_data['bintang'] = bintang
        response_data['tanggal'] = datetime.now().strftime("%m-%d-%Y")

        Review.objects.create(produk = selectedProduct, pengulas = request.user,
        headline = headline, ulasan = ulasan, bintang = bintang)
        return JsonResponse(response_data)

@login_required(login_url="/login")
def cariNamaAkun(request): 
    user = request.user
    return render(request, 'cariUsername.html')

def searchUsername(request):
    usr_name = request.GET['q']
    data = {}
    if usr_name:
        users = User.objects.filter(username__icontains=usr_name)
        if users.exists():
            data = list(users.values())
            return JsonResponse(data, safe=False)

    else:
        users = User.objects.all()
    return JsonResponse(data, safe=False)

homepage/templates/apd.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Bye-Covid! {% endblock %}
{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid padding top-hand">
    <h1 class="title" style="padding-top: 5%; color: black;">don't forget<br>to protect your body.</h1>
</div>

<!-- <div class="container-fluid padding mid">
    <div class="row text-center padding">
        <div class="col-sm-6">
            <img src="{% static 'apd2.jpg' %}" alt="APD" class="APD" width="400" height="400" style="text-align: left;">
        </div>
        <div class="col-sm-6 definition">
            <h3>Wayya APD</h3>
        </div>
    </div>
</div> -->
<!-- yang bawah gabisa tampil masa -->
<div class="container-fluid padding mid">
    <div class="row text-center" id="product">
        {% for i in apd_list %}
        <div class="col-sm-6 col-md-4 boxdown">
            <a href="/product/{{i.id}}">
                <img src={{i.gambar}} alt="apd" class="expad" width= "400" height="400">
                        <h3>{{i.nama}}</h3>
                        <p>Rp{{i.harga}}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <h3 style="text-align: center; padding-top: 2cm;">Maaf, anda harus login terlebih dahulu</h3>
    {% endif %}
{% endblock %}

homepage/templates/handsanitizer.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Bye-Covid! {% endblock %}
{% block content %}
{% if user.is_authenticated %}

<div class="container-fluid padding top-hand">
    <h1 class="title" style="padding-top: 5%; color: black;">don't forget<br>to sanitize your hands.</h1>
</div>

<div class="container-fluid padding mid">
    <div class="row text-center" id= "product">
        {% for i in handsanitizer_list %}
        <div class="col-sm-6 col-md-4 boxdown">
            <a href="/product/{{i.id}}">
                <img src={{i.gambar}} alt="hand-sanitizer" class="expad" width= "400" height="400">
                    <!-- <div class="hover-overlay"></div>
                    <div class="hover-2-content px-5 py-4"> -->
                        <h3>{{i.nama}}</h3>
                        <p>Rp{{i.harga}}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% else %}
    <h3 style="text-align: center; padding-top: 2cm;">Maaf, anda harus login terlebih dahulu</h3>
    {% endif %}
{% endblock %}

homepage/templates/reviewPage.html
{% extends 'base.html' %}
{% load static %}
  
{% block title %} 
Review Page
{% endblock %}


    {% block content %}
    <br>
    <br>
    <div class="container-fluid mb-5 pb-5" style="background: rgba(255, 254, 250, 0.9);; box-shadow: 4px 4px 20px rgba(0, 0, 0, 0.25);">
        <div class="row pt-5 mt-5 pl-5 ml-5">
          <div class="col-md-12">
            <h2>{{selectedProduct.nama}}</h2>
            <br>
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <img src="{{ selectedProduct.gambar }}" 
            alt="ProductImage" class="img-fluid mx-auto d-block">
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <div class="d-flex justify-content-center">
              <a href="#formReview"><button type="button" class="btn btn-outline-secondary" >Make Review</button></a>
            </div>
          </div>
        </div>
    </div>

    <section id="userrating">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Average User Rating</h2>
            <br>
            {% if average > 0 %}
              <h2 style="font-size: 50px;" class="text-left pl-5 ml-3">{{average}}/5.00</h2>
            {% else %}
              <h2 style="font-size: 50px;" class="text-left pl-5 ml-3">NoRating</h2>
            {% endif %}
          </div>
          <div class="col-md-6">
            <h2>Rating Breakdown</h2>
            <br>
            <div class="row">
              <div class="col-md-1">
                <h5>5</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 100%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang5}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>4</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 80%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang4}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>3</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 60%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang3}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>2</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 40%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang2}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>1</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 20%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang1}}</h5>
              </div>
            </div>

          </div>
        </div>
        </div>
        <hr style="border: 1px solid #000000;">
    </section>
    
    <section id="reviews">
      <div class="container-fluid pt-5">
        <div class="row">
          <div class="col ml-5">
            <h2>All Reviews</h2>
          </div>
        </div>
      </div>
      {%for i in review%}
      <div class="container pt-5">
        <div class="row">
          <div class="col-md-4 ml-5">
            <h2 style=" font-size: 50px;">{{i.bintang}}.0</h2>
            {%if i.bintang == 0 %}
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 1 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 2 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 3 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 4 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 5 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
            {% endif %}
          </div>
          <div class="col-md-5 mr-5 ml-5">
            <h5 style="font-size: 25px;"><b>{{i.headline}} <i>- {{i.pengulas}} </i></b></h5>
            <h6 style="font-size: 18px; text-align: justify;">{{i.ulasan}}</h6>
            <h6><b>{{i.tanggal}}</b></h6>
          </div>
        </div>
      </div>
      <br>
      <hr>
      {% endfor %}
      <div id="dataReview"></div>
      <hr style="border: 1px solid #000000;">
    </section>
  <section class="form" id="formReview">
  {% if user.is_authenticated %}
    <div class="container-fluid pb-5 mt-5">
      <form method="POST" id="reviewForm">
        {% csrf_token %}
        <div class="row">
          <h2>Review Now</h2>
        </div>
        <div class="row pt-5">
          <div class="col-md-6">
            <h4> <i class="fas fa-envelope"></i> Title</h4>
            <div id="headline">{{form.headline}}</div>
            <br>
            <h4> <i class="fas fa-envelope"></i> Your Message</h4>
            <div id="ulasan">{{form.ulasan}}</div>
            <br>
            <h4>Rate Us</h4>
            <div id="bintang">{{form.bintang}}</div>
            <div id="tanggal">{{form.tanggal}}</div>
          </div>
        </div>
        <div class="row pt-5">
          <input type = "submit" onclick="myFunction()" id='submitReview' class="btn btn-dark mx-auto" value="Submit" style="font-size: 20px;" >
          <script>
            function myFunction() {
              alert("Review anda berhasil ditambahkan!");
            }
            </script>
        </div>
      </form>
    </div>
  {% else %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <h4>You have to Login first to fill the form</h4>
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <div class="col-md-2">
                <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-secondary">Back to Login Page</button></a>
            </div>
        </div>
    </div>
  </section>
  {% endif %}
  {% endblock %}

  {% block script %} 
    <script src="https://kit.fontawesome.com/a48052e337.js" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).on('submit','#reviewForm', function(e){
          e.preventDefault();
          $.ajax({
            type: 'POST',
            url: "{% url 'postReview' postPK %}",
            data:{
              headline:$('#id_headline').val(),
              ulasan:$('#id_ulasan').val(),
              bintang:$('#id_bintang').val(),
              tanggal:$("#id_tanggal").val(),
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
              action: 'post'
            },
            success:function(json){
              $("#reviewForm").trigger('reset');
              $("#dataReview").prepend(
                '<div class="container pt-5">' + '<div class="row">' + '<div class="col-md-4 ml-5">' +
                '<h2 style=" font-size: 50px;">' + json.bintang +'.0</h2>' +'</div>' + '<div class="col-md-5 mr-5 ml-5">' 
                + '<h5 style="font-size: 25px;">' + '<b>' + json.headline + '<i>' + ' - {{ user.get_username }}' + 
                '</i>' +'</b>'+'</h5>' + '<h6 style="font-size: 18px; text-align: justify;">' + json.ulasan
                + '</h6> <h6><b>' + json.tanggal + '</h6></div></div></div><br><hr>'
              )
            },
            error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText);
            }
          })
        })

        $(".container").mouseover(function(){
          $(this).css("color","red")
        });

        $(".container").mouseout(function(){
          $(this).css("color","black")
        });
        
    </script>
    
{% endblock %}